

export type currentWeather = {
    time?: Date,
    wind_gusts_10m?: number,
    wind_direction_10m?: number,
    wind_speed_10m?: number,
    cloud_cover?: number,
    weather_code?: number,
}
export type hourlyWeather = {
    time: Date[],
    temperature_2m: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_1000hPa: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_950hPa: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_925hPa: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_850hPa: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_700hPa: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_600hPa: Float32Array<ArrayBufferLike> | null | undefined,
    weather_code: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_10m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_80m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_120m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_180m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_10m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_80m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_120m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_180m?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_gusts_10m?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_1000hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_975hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_950hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_925hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_900hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_850hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_800hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_700hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    cloud_cover_600hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_975hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_900hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_800hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_800hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_850hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_900hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_925hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_950hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_975hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_1000hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_700hPa?: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_600hPa?: Float32Array<ArrayBufferLike> | null | undefined,
}

export type fifteenMinuteWeather = {
    time: Date[],
    wind_speed_10m: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_80m: Float32Array<ArrayBufferLike> | null | undefined,
    wind_speed_120m: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_10m: Float32Array<ArrayBufferLike> | null | undefined,
    wind_direction_80m: Float32Array<ArrayBufferLike> | null | undefined,
    wind_gusts_10m: Float32Array<ArrayBufferLike> | null | undefined,
    visibility: Float32Array<ArrayBufferLike> | null | undefined,
}